Add some file
rbd3/hello-microverses pull request #1
Opened 2023-03-21 17:29 UTC by rbd3

adding readme.md, gitignore, index.html, style.css.

2023-03-21 18:03 UTC, shella12 requested changes
Hi @rbd3 , 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

- Correct use of git flow ✅ 
- All required files are added

## Required Changes ♻️

- [x] Great job on setting linter files however please make sure there aren't any linter errors reported and all linter checks on the github are green. AKA: Linter should report NO errors.


<img width="683" alt="Screenshot 2023-03-21 at 10 46 29 PM" src="https://user-images.githubusercontent.com/44798044/226700936-8e5352aa-fb4b-45b5-a072-7ca84f3a2131.png">

_Check the comments under the review._

## Optional suggestions

- [ ] [OPTIONAL] Please use descriptive commit messages. The commit message should be written in the imperative tense (which you have done 👍 ) and capitalized e.g. instead of` fix stylint error` say  ` Fix stylint error`. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8). Its one of the requirements of the project but please try to keep this in mind for future

<img width="673" alt="Screenshot 2023-03-21 at 10 47 17 PM" src="https://user-images.githubusercontent.com/44798044/226698256-92ad2c1b-6375-4e44-b991-71c316920d20.png">

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 18:03 UTC, shella12 commented on README.md
> +# Hello-Microverse
- [ ] Please remove duplicate headings from your README as this makes your README look cluttered

2023-03-21 18:03 UTC, shella12 commented on README.md
> +- [📝 License](#license)
- [ ] I can see that you are using Microverse README template to document your project in your README. But there are some sections missing. Please refer to [this template](https://github.com/microverseinc/readme-template) and make sure all of the main sections are added to your README. The only section that is OPTIONAL is FAQ. You can always skip it if you want to. Remember to customize the template to your project as well.

2023-03-21 18:03 UTC, shella12 commented on linters.yml
- [ ] Please make sure to remove duplicate `linters.yml` file from project directory. `linters.yml` is only suppose to be copied into `.github/workflows` folder.  

<img width="718" alt="Screenshot 2023-03-21 at 10 44 47 PM" src="https://user-images.githubusercontent.com/44798044/226699882-23e71afb-6c2b-4d58-87f8-f8d8b878f4e0.png">

2023-03-22 06:34 UTC, rbd3 commented on README.md
> +# Hello-Microverse
@shella12 
i removed this duplicated headings.

2023-03-22 06:35 UTC, rbd3 commented on README.md
> +- [📝 License](#license)
@shella12 
i made some additions in my README

2023-03-22 06:38 UTC, rbd3 commented on linters.yml
@shella12 
i did it

2023-03-22 09:04 UTC, braincee approved these changes
Hi @rbd3 , I am @braincee, your Code Reviewer.

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![youre-approved-shirley-auto-group](https://user-images.githubusercontent.com/78104544/226852457-95ef4c1d-5d51-4f76-abd8-1fdc06b89e77.gif)

OPTIONAL CHANGES
---

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @braincee._

---

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-22 09:04 UTC, braincee commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] [OPTIONAL] Please remove the live demo link since you have not deployed your project.

2023-03-22 09:04 UTC, braincee commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/andry-narson-rabedesana-15b8b4248)
- [ ] [OPTIONAL] Please add your username of social media links inside [] brackets

2023-03-23 05:28 UTC, merged